### PR TITLE
Upgrade to Grails 4

### LINKED ISSUE #7: [grails4] Application fails to start up - required bean 'saltSource' missing
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an application with Grails 4.0.0.M2
2. Add the Spring Security OAuth2 Plugin according to directions

OR 

1. Start with working Grails 3.3.9 application + Spring Security OAuth2 integration
2. Attempt to upgrade to Grails 4.0.0.M2

### Expected Behaviour

The application starts

### Actual Behaviour

```
2019-03-28 19:14:27.880 ERROR --- [  restartedMain] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'oauth2BasicAuthenticationFilterRegistrationBean': Cannot resolve reference to bean 'oauth2BasicAuthenticationFilter' while setting bean property 'filter'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'oauth2BasicAuthenticationFilter': Cannot resolve reference to bean 'clientAuthenticationManager' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clientAuthenticationManager': Cannot resolve reference to bean 'clientCredentialsAuthenticationProvider' while setting constructor argument with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clientCredentialsAuthenticationProvider': Cannot resolve reference to bean 'saltSource' while setting bean property 'saltSource'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'saltSource' available
2019-03-28 19:14:28.063 ERROR --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean named 'saltSource' that could not be found.


Action:

Consider defining a bean named 'saltSource' in your configuration.


Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```

### Environment Information

- **Operating System**: Fedora 29 Workstation
- **GORM Version:** 7.0.0.RC2
- **Grails Version (if using Grails):** 4.0.0.M2
- **JDK Version:** openjdk version 1.8.0_201

### Example Application

- TODO: link to github repository with example that reproduces the issue

### PR DESCRIPTION
**Pull request by joemccall86**
This fixes https://github.com/grails-plugins/grails-spring-security-oauth2-provider/issues/7 for me, but the tests currently do not run.

Background: we need to utilize this plugin for our application. Ignoring the tests, this fix allows us to move forward with our application tests. I think there's still more work to make the existing tests for this project work with Grails 4, but at the very least the plugin is functional.

Summary:
* Upgrade Grails to 4.0
* Upgrade GORM to 7.0.1
* Upgrade Gradle to 5.1
* Update unit tests to use the new testing trait support

### CODE REVIEW

**Comment by bluesliverx** [comment]
The tests not running in Travis is my fault, getting a fix ready for this...

**Comment by bluesliverx** [comment]
I'll see if the travis build works or not, but it should remain working on the master branch. But if you rebase on the current master (https://github.com/grails-plugins/grails-spring-security-oauth2-provider/commit/cd604ff5c28a51682e226e628b7bdf5ac4d792ac), you should see tests actually try to run in travis for this PR now @joemccall86.

**Comment by joemccall86** [comment]
I just fixed the unit tests. Note that since Grails 3.3 I cannot test uniqueness constraints in a unit test. Our project uses integration tests for that. Those tests appear to be ignored anyway. 

Some of the integration tests run too, though I think the acceptance tests need to have the application running already.

**Comment by bluesliverx** [comment]
Thanks @joemccall86! Is this backwards compatible or does it need a new major version since it won't work with 3?

**Comment by joemccall86** [comment]
I think it'll need a new version number for sure since the Grails dependency has changed, though the changes to the tests should be backwards-compatible. How do you want me to handle this?

**Comment by bluesliverx** [comment]
Just up the major version in spring-security-oauth2-provider/build.gradle.

**Comment by bluesliverx** [comment]
This has been released as 4.0.0-RC1. Try it out and let me know. If it ends up working, I'll re-release as 4.0.0.

Actually, @joemccall86, the documentation is not building correctly.  See the travis build: https://travis-ci.org/grails-plugins/grails-spring-security-oauth2-provider/builds/561056104

**Comment by joemccall86** [comment]
I'm not exactly sure what's going on with the documentation. It could be related to the upgrade to Gradle 5.

That said, 4.0.0-RC1 appears to work for me.

**Pull request merged**
